#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export DIST_PATH="${DIR}"
CUSTOM_PI_OS_PATH=$(<"${DIR}"/custompios_path)
BASE_BOOT_MOUNT_PATH=boot
export CUSTOM_PI_OS_PATH
export BASE_BOOT_MOUNT_PATH
export PATH=$PATH:$CUSTOM_PI_OS_PATH

echo "Installing CustomPiOS dependencies..."
apt-get install -y --no-install-recommends \
        ca-certificates \
        sudo \
        build-essential \
        sudo \
        curl \
        git \
        wget \
        p7zip-full \
        python3 \
        python3-distutils \
        python3-dev \
        python3-git \
        binfmt-support \
        qemu-system \
        qemu-user \
        qemu-user-static \
        sudo \
        file \
        fdisk \
        btrfs-progs \
        jq \
        zip \
        xz-utils \
        lsof \
        mc\
        f2fs-tools

"${CUSTOM_PI_OS_PATH}"/build_custom_os "$@"
