name: Build RatOS - Raspberry Pi OS buster
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
    paths: [src/**]
  pull_request:
    types: [opened, edited]
    paths: [src/**]
  workflow_dispatch:

jobs:
  raspiosbuild:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: sudo apt update; sudo apt install coreutils p7zip-full qemu-user-static zip

      - name: Checkout CustomPiOS
        uses: actions/checkout@v2
        with:
          repository: "guysoft/CustomPiOS"
          path: CustomPiOS

      - name: Checkout RatOS Project
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          path: repository
          submodules: true

      - name: Download Raspberry Pi OS Source Image
        run: aria2c -d repository/src/image/ --seed-time=0 https://downloads.raspberrypi.org/raspios_oldstable_lite_armhf/images/raspios_oldstable_lite_armhf-2021-12-02/2021-12-02-raspios-buster-armhf-lite.zip.torrent

      - name: Update CustomPiOS Paths
        run: cd repository/src && ../../CustomPiOS/src/update-custompios-paths

      - name: Build Image
        run: sudo modprobe loop && cd repository/src && sudo bash -x ./build_dist

      - name: Copy output image
        run: cp ${{ github.workspace }}/repository/src/workspace/*-raspios-*-lite.img RatOS-latest.img

      - name: Compress the image
        run: zip RatOS-latest.zip RatOS-latest.img

      - uses: actions/upload-artifact@v1
        with:
          name: RatOS-latest.zip
          path: RatOS-latest.zip
